@BANKA_PORT=8001
@BANKB_PORT=9001
@BRIDGE_PORT=7001

@bridge_address=0xBF4961b1b32CA8873e0C760906745F2006878EF0
@user_bankA_address=0xEDAC9E99e752107c8dE95DAd7cCD8bd0Ae352001
@user_bankB_address=0xa3df034084078EBf20216b0789CF4901D8D6194E

@allowance_size=2000
@fees=11
@collateral=10 
@tranfer_amt=10

###Bank A query balance
GET http://localhost:{{BANKA_PORT}}/balance

####
GET http://localhost:{{BANKB_PORT}}/balance


####
GET http://localhost:{{BRIDGE_PORT}}/balance


#### Send A some money
POST http://localhost:{{BRIDGE_PORT}}/transfer
User-Agent: rest-client
Content-Type: application/json
charset:UTF-8

{
     "to": "{{user_bankA_address}}",
     "amount" : 15000
}

#### Send B some money
POST http://localhost:{{BRIDGE_PORT}}/transfer
User-Agent: rest-client
Content-Type: application/json
charset:UTF-8

{
     "to": "{{user_bankB_address}}",
     "amount" : {{tranfer_amt}}
}


#### A Send B some money
POST http://localhost:{{BANKA_PORT}}/transfer
User-Agent: rest-client
Content-Type: application/json
charset:UTF-8

{
     "to": "{{user_bankB_address}}",
     "amount" : {{tranfer_amt}}
}


### Bank B creates a request for increase allowance for the bridge spend on behalf of bank B
POST http://localhost:{{BANKB_PORT}}/increase
User-Agent: rest-client
Content-Type: application/json
charset:UTF-8

{
     "spender": "{{bridge_address}}",
     "amount" : {{allowance_size}}
}


### check that the bridge has the allowance
# @name allowB
POST http://localhost:{{BRIDGE_PORT}}/allowance
Content-Type: application/json

{
    "owner": "{{user_bankB_address}}",
    "spender": "{{bridge_address}}"
}

###Bank A creates a request for increase allowance for the bridge spend on behalf of bank B
POST http://localhost:{{BANKA_PORT}}/increase
User-Agent: rest-client
Content-Type: application/json
charset:UTF-8

{
     "spender": "{{bridge_address}}",
     "amount" : {{allowance_size}}
}


###Bank A creates a request for increase allowance for the bridge spend on behalf of bank B
POST http://localhost:{{BANKA_PORT}}/decrease
User-Agent: rest-client
Content-Type: application/json
charset:UTF-8

{
     "spender": "{{bridge_address}}",
     "amount" : {{allowance_size}}
}

###Bank A creates a request for increase allowance for the bridge spend on behalf of bank B
POST http://localhost:{{BANKB_PORT}}/decrease
User-Agent: rest-client
Content-Type: application/json
charset:UTF-8

{
     "spender": "{{bridge_address}}",
     "amount" : 10000
}


###Bank A creates a request for increase allowance for the bridge spend on behalf of bank B
POST http://localhost:{{BANKA_PORT}}/increase
User-Agent: rest-client
Content-Type: application/json
charset:UTF-8

{
     "spender": "{{bridge_address}}",
     "amount" : {{allowance_size}}
}


### check that the bridge has the allowance
# @name allowA
POST http://localhost:{{BRIDGE_PORT}}/allowance
Content-Type: application/json

{
    "owner": "{{user_bankA_address}}",
    "spender": "{{bridge_address}}"
}

### 
@avail_allowance={{allowA.response.body.amt}}

### check that the bridge has the allowance
# @name allowB
POST http://localhost:{{BRIDGE_PORT}}/allowance
Content-Type: application/json

{
    "owner": "{{user_bankB_address}}",
    "spender": "{{bridge_address}}"
}


###Bridge spends allowance transfer_from Bank A to Bank B
POST http://localhost:{{BRIDGE_PORT}}/transfer_from
Content-Type: application/json

{
    "from": "{{user_bankA_address}}",
    "to": "{{user_bankB_address}}",
    "amount": {{fees}}
}


### now check the balance in A and B
GET http://localhost:{{BANKA_PORT}}/balance

###
GET http://localhost:{{BANKB_PORT}}/balance

### now create HTLC for collateral
@secret= "{{$localDatetime 'YYYY-MM-DD'}} + {{$timestamp}}"

### create htlhash
# @name htlcSecretResp
PUT http://localhost:{{BRIDGE_PORT}}/htlc/hash_secret
Content-Type: application/json

{
    "secret": "{{secret}} "
}

### HTLC secret
##@htlc={{htlcSecretResp.response.body.$.htlcSecretResp.result}}
@htlc_secret={{htlcSecretResp.response.body.result}}

####
# @name timeStamp

#for testing lets use 30 seconds
PUT http://localhost:{{BRIDGE_PORT}}/htlc/duration
Content-Type: application/json

{
      "dur_ms": 30000 
   
}

####
@duration={{timeStamp.response.body.result}}


### create and HTLCFor 
PUT http://localhost:{{BRIDGE_PORT}}/htlc/create_for
Content-Type: application/json

{
    "receiver": "{{user_bankA_address}}",
    "sender": "{{user_bankB_address}}",
    "duration": {{duration}},
    "amount" : 1,
    "secret": "{{htlc_secret}}"
}


#### get secrets for all hashlocks
GET http://localhost:{{BRIDGE_PORT}}/bridge/dump_secrets


####
@loanid="12234344"
#### close loan early
GET http://localhost:{{BRIDGE_PORT}}/bridge/closeloanearly/{{loanid}}



### look at the Active htlocks in the system
GET http://localhost:{{BRIDGE_PORT}}/htlc/active

### See all 
GET http://localhost:{{BRIDGE_PORT}}/htlc/all

### see amount on the HTLC that was created

### look at the Active htlocks in the system
# @name AactiveHTLC
GET http://localhost:{{BANKA_PORT}}/htlc/active

###
@hlock_val={{AactiveHTLC.response.body.$[-1:]}}

### amount the HTLC
GET http://localhost:{{BANKA_PORT}}/htlc/amount/{{hlock_val}}

### balance the HTLC
GET http://localhost:{{BANKA_PORT}}/htlc/balance/{{hlock_val}}

### sender the HTLC
GET http://localhost:{{BANKA_PORT}}/htlc/sender/{{hlock_val}}

### reciever the HTLC
GET http://localhost:{{BANKA_PORT}}/htlc/receiver/{{hlock_val}}

### get pre image 
GET http://localhost:{{BANKA_PORT}}/htlc/preimage/{{hlock_val}}

### get pre image 
PUT http://localhost:{{BANKA_PORT}}/htlc/refund/{{hlock_val}}

### get pre image 
POST http://localhost:{{BANKA_PORT}}/htlc/withdraw/{{hlock_val}}
Content-Type: application/json

{ "htlc":"{{hlock_val}}", 
  "preimage":""
}

### 
GET http://localhost:{{BANKA_PORT}}/htlc/preimage/0xFCc3c6B1Ea0111fFF9D0007D52dE5266583d3ae2



### look at the Active htlocks in the system
GET http://localhost:{{BANKB_PORT}}/htlc/active

### See all 
GET http://localhost:{{BANKA_PORT}}/htlc/all
### See all 
GET http://localhost:{{BANKB_PORT}}/htlc/all

### see amount on the HTLC that was created


GET http://localhost:{{BRIDGE_PORT}}/htlc/amount/{{htlc}}

### get the balance
GET http://localhost:{{BRIDGE_PORT}}/htlc/balance/{{htlc}}


### get the spender
GET http://localhost:{{BRIDGE_PORT}}/htlc/sender/{{htlc}}

### refund 
GET http://localhost:{{BRIDGE_PORT}}/htlc/refund/{{htlc}}

#seize this cant work because it requires preimaging which does not work


@KYCER_PORT=10001

#### check KYC for Bank A
GET http://localhost:{{KYCER_PORT}}/kyc/check/{{user_bankA_address}}

#### check KYC check for bridge
GET http://localhost:{{KYCER_PORT}}/kyc/check/{{bridge_address}}

#### check KYC count for bridge
GET http://localhost:{{KYCER_PORT}}/kyc/num/{{bridge_address}}

### check for bank B
GET http://localhost:{{KYCER_PORT}}/kyc/check/{{user_bankB_address}}

### grant KYC for bank A
PUT http://localhost:{{KYCER_PORT}}/kyc/grant/{{user_bankB_address}}