@BANKA_PORT=8001
@BANKB_PORT=9001
@BRIDGE_PORT=7001

@bridge_address=0xBF4961b1b32CA8873e0C760906745F2006878EF0
@user_bankA_address=0xEDAC9E99e752107c8dE95DAd7cCD8bd0Ae352001
@user_bankB_address=0xa3df034084078EBf20216b0789CF4901D8D6194E

@allowance_size=1000
@fees=100
@collateral=500 
###Bank A query balance
GET http://localhost:{{BANKA_PORT}}/balance

####
GET http://localhost:{{BANKB_PORT}}/balance

###Bank A creates a request for increase allowance for the bridge spend on behalf of bank B
POST http://localhost:{{BANKA_PORT}}/increase
User-Agent: rest-client
Content-Type: application/json
charset:UTF-8

{
     "spender": "{{bridge_address}}",
     "amount" : {{allowance_size}}
}

### check that the bridge has the allowance
# @name allow
POST http://localhost:{{BRIDGE_PORT}}/allowance
Content-Type: application/json

{
    "owner": "{{user_bankA_address}}",
    "spender": "{{bridge_address}}"
}

### 
@avail_allowance={{allow.response.body.amt}}

###Bridge spends allowance transfer_from Bank A to Bank B
POST http://localhost:{{BRIDGE_PORT}}/transfer_from
Content-Type: application/json

{
    "from": "{{user_bankA_address}}",
    "to": "{{user_bankB_address}}",
    "amount": {{fees}}
}


### now check the balance in A and B
GET http://localhost:{{BANKA_PORT}}/balance

###
GET http://localhost:{{BANKB_PORT}}/balance

### now create HTLC for collateral
@secret= "{{$localDatetime 'YYYY-MM-DD'}} + {{$timestamp}}"


### create htlhash
# @name htlcSecretResp
PUT http://localhost:{{BRIDGE_PORT}}/htlc/hash_secret
Content-Type: application/json

{
    "secret": {{secret}} 
}

### HTLC secret
##@htlc={{htlcSecretResp.response.body.$.htlcSecretResp.result}}
@htlc={{htlcSecretResp.response.body.result}}

####
# @name timeStamp

#for testing lets use 30 seconds
PUT http://localhost:{{BRIDGE_PORT}}/htlc/duration
Content-Type: application/json

{
    "dur_ms": 30000 
}

####
@duration={{timeStamp.response.body.result}}

#### create HTLC for
# @name htlcreate
POST http://localhost:{{BRIDGE_PORT}}/htlc/create_for
Content-Type: application/json

{ "sender":"{{user_bankA_address}}", 
  "receiver":"{{user_bankB_address}}", 
  "secret":"{{htlc}}", 
  "duration":"{{duration}}",
  "amount": {{collateral}}
}

###

@htlock = {{htlcreate.response.body.$.htlcreate.result}}


###get pre image  - THIS CALL FAILS
# @name getpreimage
GET http://localhost:{{BRIDGE_PORT}}/htlc/preimage/:{{htlc}}


@preimage={{getpreimage.response.body.result}}

### look at the Active htlocks in the system
GET http://localhost:{{BRIDGE_PORT}}/htlc/active

### See all 
GET http://localhost:{{BRIDGE_PORT}}/htlc/all

### see amount on the HTLC that was created

GET http://localhost:{{BRIDGE_PORT}}/htlc/amount/:{{htlc}}

### get the balance
GET http://localhost:{{BRIDGE_PORT}}/htlc/balance/:{{htlc}}


### get the spender
GET http://localhost:{{BRIDGE_PORT}}/htlc/sender/:{{htlc}}

### refund 
GET http://localhost:{{BRIDGE_PORT}}/htlc/refund/:{{htlc}}

#seize this cant work because it requires preimaging which does not work


@KYCER_PORT=10001

#### check KYC for Bank A
GET http://localhost:{{KYCER_PORT}}/kyc/check/:{{user_bankA_address}}

#### check KYC check for bridge
GET http://localhost:{{KYCER_PORT}}/kyc/check/:{{bridge_address}}

#### check KYC count for bridge
GET http://localhost:{{KYCER_PORT}}/kyc/num/:{{bridge_address}}

### check for bank B
GET http://localhost:{{KYCER_PORT}}/kyc/check/:{{user_bankB_address}}

### grant KYC for bank A
PUT http://localhost:{{KYCER_PORT}}/kyc/grant/:{{user_bankB_address}}